### ISSUE TITLE
About OGB submission

### ISSUE THREAD

**Issue by weihua916** [microsoft/Graphormer#1]
Thank you for your leaderboard submission. Please provide the exact command to reproduce your leaderboard results.

**Comment by zhengsx** [comment]
> Thank you for your leaderboard submission. Please provide the exact command to reproduce your leaderboard results.

Hi Weihua, thanks for organizing the amazing event! Here is the exact command which can reproduce our result:
[https://github.com/microsoft/Graphormer/tree/ogb-lsc/OGB-LSC](https://github.com/microsoft/Graphormer/tree/ogb-lsc/OGB-LSC)

Please kindly let us know if you have problem on reproduction.

**Comment by weihua916** [comment]
I see. I actually meant the code for reproducing ogbg-molhiv and ogbg-molpcba.

**Comment by zhengsx** [comment]
> I see. I actually meant the code for reproducing ogbg-molhiv and ogbg-molpcba. We can update the leaderboard once we confirm that you provide the sufficient instruction to reproduce your results.

Oh, sure. The final code will be released in about couple of weeks. Still need to do some paper works for the release process. Will let you know immediately.

**Comment by chao1224** [comment]
Hi authors, thanks for sharing this. I'm also wondering when the code for `OGB-LSC` will be released.

**Comment by zhengsx** [comment]
> I see. I actually meant the code for reproducing ogbg-molhiv and ogbg-molpcba (the original OGB, not OGB-LSC). We can update the leaderboard once we confirm that you provide the sufficient instruction to reproduce your results.

Hi Weihua, we just released the first version of our code, which provides full descriptions and scripts to reproduce all of our experiments.

**Comment by weihua916** [comment]
Thank you! Updated the leaderboard!
