### ISSUE TITLE
Node classification

### ISSUE THREAD

**Issue by steelman97** [microsoft/Graphormer#12]
What do I have to modify the code in order to try the model on ogbn-proteins? (Wrapper, collator..)

**Comment by chengxuanying** [comment]
Hi @steelman97 ,
I think writing a new dataset for node tasks is better. Please refer to the [class MyGraphPropPredDataset](https://github.com/microsoft/Graphormer/blob/569f0d90824e9e7596257b0cdebd75216b5fb0a8/graphormer/wrapper.py#L59) if you want to do so.

There are some tips for trying the model on ogbn-proteins:
1. Implement a proper graph sampling strategy as mentioned in our paper.
2. Some parts of the code need to rewrite to fit for larger graph. (E.g., the floyd-warshall algorithm is n^3 regarding the number of nodes, you may need to choose an alternative metric for efficient spatial encoding.)
