### ISSUE TITLE
graph_prediction.py calls the EpochShuffleDataset method with wrong parameters name

### ISSUE THREAD

**Issue by chrisxu2016** [microsoft/Graphormer#131]
https://github.com/microsoft/Graphormer/blob/bdbbe6613a8392688babc825e20b1173ae82d6f7/graphormer/tasks/graph_prediction.py#L215

As the title says, here should be num_samples instead of size

**Comment by mavisguan** [comment]
Thanks for helping us finding out the bug, we'll fix this soon.
