### ISSUE TITLE
About attention bias padding in collator.py

### ISSUE THREAD

**Issue by Voldet** [microsoft/Graphormer#141]
Hi, thanks for the code! Your article has inspired me a lot.

However, when I read the code you wrote, I have a question about the padding process of attention bias.

The original code of attention bias padding is as follows:
```
def pad_attn_bias_unsqueeze(x, padlen):
    xlen = x.size(0)
    if xlen < padlen:
        new_x = x.new_zeros([padlen, padlen], dtype=x.dtype).fill_(float("-inf"))
        new_x[:xlen, :xlen] = x
        new_x[xlen:, :xlen] = 0
        x = new_x
    return x.unsqueeze(0)
```
My question is why ```new_x[xlen:, :xlen] = 0``` is needed?

Thanks!

**Comment by jndean** [comment]
A softmax is performed over dimension 1 of the attention matrix in a transformer.
In rows corresponding to padding nodes, if the whole row was full of -inf then the denominator in the softmax would be `n_cols * exp(-inf) = 0`, causing a divide-by-zero exception. So instead some values in the row are set to 0, an arbitrary finite value.
