### ISSUE TITLE
Question about edge attention

### ISSUE THREAD

**Issue by WangYong-Design** [microsoft/Graphormer#145]
Hi, thanks for the code! Your article has inspired me a lot.

However, when I read the code you wrote, I have a question about the edge attention.

I think the following lines of code correspond to the code in the paper that computes the attention of edges,but I don't quite understand why torch.mm is along the dimension of num_heads. 
Does this mean that the dimension of the edge embedding is num_heads dimension?

![image](https://user-images.githubusercontent.com/71626073/196693743-40e4028e-35cb-4250-b663-20d171db4516.png)
![image](https://user-images.githubusercontent.com/71626073/196693820-ac5fc14c-a866-42ad-a5d2-045919ab94e3.png)

**Comment by zhengsx** [comment]
The shape of attention bias is same with attention weight matrix, thus the head dimension should also be considered.

**Comment by WangYong-Design** [comment]
Thanks.got it!
