### ISSUE TITLE
Example does not work - Segmentation fault 

### ISSUE THREAD

**Issue by doloresgarcia** [microsoft/Graphormer#146]
When running the example zinc.sh a 'Segmentation fault' appears, uninstalling setuptools is not an option (not root) , and it does not seem to solve the issue for many users. Could you provide a solution?

**Comment by surajgattani** [comment]
@doloresgarcia How did you solve this issue? I am getting the same error.

**Comment by doloresgarcia** [comment]
I resolved it by doing a careful pytorch + pytorch_geometric installation, so not using the install.sh but rather checking what pytorch works with your drivers and then following the pytorch install commands:
https://pytorch.org/
and not using cuda 11.7 
so my current env looks like:

```
torch                     1.11.0+cu113             pypi_0    pypi
torch-geometric           2.1.0.post1              pypi_0    pypi
torch-scatter             2.0.9                    pypi_0    pypi
torch-sparse              0.6.15                   pypi_0    pypi
torchaudio                0.11.0+cu113             pypi_0    pypi
torchvision               0.12.0+cu113
```

**Comment by surajgattani** [comment]
Thanks @doloresgarcia. I will try it
