### ISSUE TITLE
how to speed up one epoch

### ISSUE THREAD

**Issue by linzhenyuyuchen** [microsoft/Graphormer#17]
hello,  
  Thank you for your sharing , this is a great work!
  When i trained my data with your code, i found a problem.
  When every epoch starts, it needs to wait for a long time to see the GPU utilization rised up..
  What may be the reason for this ?

**Comment by chengxuanying** [comment]
Hi @linzhenyuyuchen ,
We have not met this problem.
Could you provide a python profile to help determine the lag part?
