### ISSUE TITLE
Missing file train_cli.sh

### ISSUE THREAD

**Issue by Mochimo-mo** [microsoft/Graphormer#185]
Hi,
I'm currently trying to run protein-ligand part in DIG, but I encountered an error while attempting to run **single_datapoint_sampling.sh**. I discovered that the issue seems to stem from a missing **./examples/diffusion/train_cli.sh** file.
Could you kindly advise me on where I might obtain this file? 
Thank you very much for your assistance.

**Comment by pvrancx** [comment]
same error. distributional_graphormer/protein-ligand/src/evaluation/single_datapoint_sampling.sh script tries to call this missing file

**Comment by volltin** [comment]
Hi @Mochimo-mo and @pvrancx,
Thanks for pointing this out. The missing train_cli.sh file has been added in #193 . Please update your repo to the latest commit to resolve the issue.
