### ISSUE TITLE
For multimeric protein structure

### ISSUE THREAD

**Issue by jongseo-park** [microsoft/Graphormer#189]
Hi,

I used this tool for protein analysis. 

I successfully extracted single and pair representations of my target protein using the local version of AlphaFold. 
and performed structural distribution analysis with the pickle file containing these representations.

When I run this tool for a monomeric target, it works fine. However, for a multimeric protein, the output structure appears tangled. I provided a FASTA file with concatenated protein sequences, and the lengths and dimensions of the arrays seem correct.

Why does this code not work well for multimeric proteins?

**Comment by zhengsx** [comment]
Currently it doesn't support complex yet.
