### ISSUE TITLE
Unable to Download Sample Data

### ISSUE THREAD

**Issue by R-Laksh** [microsoft/Graphormer#191]
There appears to be an issue with installing the sample data. When running `wget https://ai4scienceasiaedp.blob.core.windows.net/dig/dig/protein/dataset/protein-dataset.tar.gz$SAS -O protein-dataset.tar.gz` the following error occurs

` --2024-05-24 11:15:15--  https://ai4scienceasiaedp.blob.core.windows.net/dig/dig/protein/dataset/protein-dataset.tar.gz
Resolving ai4scienceasiaedp.blob.core.windows.net (ai4scienceasiaedp.blob.core.windows.net)... 20.60.153.1
Connecting to ai4scienceasiaedp.blob.core.windows.net (ai4scienceasiaedp.blob.core.windows.net)|20.60.153.1|:443... connected.
HTTP request sent, awaiting response... 409 Public access is not permitted on this storage account.
2024-05-24 11:15:16 ERROR 409: Public access is not permitted on this storage account..`

This error occurs for all example links in the DiG folder, including for the checkpoints. Additionally, the error occurs across devices

**Comment by zhengsx** [comment]
Please add SAS for downloading. You may refer to the [Readme](https://github.com/microsoft/Graphormer/tree/main/distributional_graphormer#code-and-model).

**Comment by YaoHuUstc** [comment]
SAS="?sv=2021-10-04&st=2024-04-03T07%3A48%3A36Z&se=2025-04-04T07%3A48%3A00Z&sr=c&sp=rl&sig=TcaroWm0i9P2heueVCRbrUgTRX4SBbN%2BmpqlA3087JY%3D"
wget https://ai4scienceasiaedp.blob.core.windows.net/dig/dig/protein/dataset/protein-dataset.tar.gz$SAS -O protein-dataset.tar.gz

when I add SAS for downloading the error still occur

--2024-07-07 15:58:05--  https://ai4scienceasiaedp.blob.core.windows.net/dig/dig/protein/dataset/protein-dataset.tar.gz?sv=2021-10-04&st=2024-04-03T07%3A48%3A36Z&se=2025-04-04T07%3A48%3A00Z&sr=c&sp=rl&sig=TcaroWm0i9P2heueVCRbrUgTRX4SBbN%2BmpqlA3087JY%3D
Resolving ai4scienceasiaedp.blob.core.windows.net (ai4scienceasiaedp.blob.core.windows.net)... 20.60.153.1
Connecting to ai4scienceasiaedp.blob.core.windows.net (ai4scienceasiaedp.blob.core.windows.net)|20.60.153.1|:443... connected.
HTTP request sent, awaiting response... 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
2024-07-07 15:58:07 ERROR 403: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature..

The error become 403

**Comment by guruace** [comment]
@YaoHuUstc I had the same problem. No solution?

**Comment by zhengsx** [comment]
#194

**Comment by amelie-iska** [comment]
Did anyone ever figure out how to get the data?
