### ISSUE TITLE
PreTrained Models

### ISSUE THREAD

**Issue by AmeenAli** [microsoft/Graphormer#25]
Hello!
<br>
Any chance uploading a PreTrained models for the different experiments ?
Thanks a lot!

**Comment by AmeenAli** [comment]
Hi,
Thanks!
Anything new with this?

**Comment by zhengsx** [comment]
> Hi, Thanks! Anything new with this?

Very soon.

**Comment by zhengsx** [comment]
The pre-trained models are now available in the v2.0 release. Close this issue. Feel free to raise a new one or reopen this one for any further question.

**Comment by AmeenAli** [comment]
Hi,
Thanks!
where is the link?

**Comment by zhengsx** [comment]
You can have a look at the docs: https://graphormer.readthedocs.io/en/latest/Quick-Start.html#evaluate-pre-trained-models .
