### ISSUE TITLE
Report errors from pytorch_lightning

### ISSUE THREAD

**Issue by zaixizhang** [microsoft/Graphormer#27]
I follow the conda setup in the readme file. However one error happens when importing pytorch_lightning:
![image](https://user-images.githubusercontent.com/52197241/139679189-326b6338-c710-4a30-adfb-fecd98e424b0.png)
Could you give me some ideas how to fix it? Thanks!

**Comment by zhengsx** [comment]
Seems like a compatibility issue with PyTorch, CUDA and Pytorch_Lighting. See similar issues with pytorch [issues](https://github.com/search?q=_ZTIN3c1021AutogradMetaInterfaceE&type=issues).

**Comment by zaixizhang** [comment]
Thanks for your reply! Have fixed this problem.
