### ISSUE TITLE
A question about the file model.py

### ISSUE THREAD

**Issue by linjc16** [microsoft/Graphormer#29]
model.py Line 114
`in_degree, out_degree = batched_data.in_degree, batched_data.in_degree`
?

**Comment by zhengsx** [comment]
Right now, the examples in Graphormer repo are mainly about molecular modeling, where we view molecular graph as undirectional graph. Hence the out_degree == in_degree == degree. If you want to try directional graph with different in/out degree encoding, just modify Line114 by yourself.

**Comment by linjc16** [comment]
Got it. Thank u. :)

> Right now, the examples in Graphormer repo are mainly about molecular modeling, where we view each molecular graph as one undirectional graph. Hence the out_degree == in_degree == degree. If you want to try directional graph with different in/out degree encoding, just modify Line114 by yourself.
