### ISSUE TITLE
_pickle.UnpicklingError when attempting to load 3D position file

### ISSUE THREAD

**Issue by Dinxin** [microsoft/Graphormer#3]
![image](https://user-images.githubusercontent.com/19572535/122641296-fa237900-d136-11eb-9d41-7c9c330d9311.png)

**Comment by diggerdu** [comment]
https://github.com/microsoft/Graphormer/pull/5

**Comment by zhengsx** [comment]
Seems like a version mismatch issue. Could you provide a minimal reproducible example with details of package version?

**Comment by zhengsx** [comment]
Close this issue due to inactivity for a long time. Feel free to reopen it if the problem still exist.
