### ISSUE TITLE
Report errors with validation dataloader

### ISSUE THREAD

**Issue by zaixizhang** [microsoft/Graphormer#30]
Hi, I try to reproduce the results on ogb-lsc. It report errors at the 90% iteration of the first epoch. It seems there is something wrong with the validation dataloader. Could you give me some suggestions to fix it? Thanks!
![image](https://user-images.githubusercontent.com/52197241/140734559-69a10f52-97eb-4654-90d2-fe43e45fba4b.png)

**Comment by zhengsx** [comment]
Are your environment same as the requirement? Could you provide a minimal reproducible example with detailed package version information? In addition, could you try to set num_workers=1 to see the error message?

**Comment by zaixizhang** [comment]
Thanks for your reply! Previously, my pytorch-lightning version is 1.4.2. After changing to 1.3.0, it works.

Thanks for your help!
