### ISSUE TITLE
Training Graphormer-Small on dataset PCQM4M and Understanding of Edge Encoder

### ISSUE THREAD

**Issue by meloncolie** [microsoft/Graphormer#32]
Hello,
I have read your code and have some question.
1. How to train Graphormer-Small on dataset PCQM4M, could you provide a sample? e.g. shell code
2. How to understand the dimension nn.Embedding(512 * 3 + 1, num_heads, padding_idx=0) of edge encoder? The shape  of edge_input at the end of the function collator in colloator.py (before making a Batch format) is [n_graph, n_node, n_node, multi_hop_max_dist, n_edge_features], where n_edge_features=3. So how do the multiplication with 512 and the addition with 1 come?
Thanks a lot!

**Comment by zhengsx** [comment]
1. the shell code could be refer to [this](https://github.com/microsoft/Graphormer/tree/main/examples/ogb-lsc#example-usage), by replacing the `--n_layers=12` to 6, and other hyper-parameters described in Table 7 in the [paper](https://arxiv.org/pdf/2106.05234.pdf).
2. the first dimension of nn.Embedding is the vocabulary size, and edge feature is the category feature, which means the vocabulary size should be greater than the number of the class of all categories (all 3 edge feature dimensions).

**Comment by zhengsx** [comment]
Close this issue due to inactive. Feel free to raise a new one or reopen this one for any further question.
