### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by MattMcPartlon** [microsoft/Graphormer#33]
https://github.com/microsoft/Graphormer/blob/740e6ff09a5de29d61def5ea6af7dfd04cee719e/graphormer/model.py#L114

This line has an obvious error. Thought you may want to know.

**Comment by zhengsx** [comment]
Hi, please refer to this issue: #29

**Comment by zhengsx** [comment]
Close this issue due to inactive. Feel free to raise a new one or reopen this one for any further question.
