### ISSUE TITLE
I don't know the effect of adding offset to the x feature  in datapreprocess

### ISSUE THREAD

**Issue by huahuaai** [microsoft/Graphormer#36]

**Comment by zhengsx** [comment]
Could you provide more detailed description about your question, including the reference code?

**Comment by huahuaai** [comment]
`def convert_to_single_emb(x, offset=512):
    feature_num = x.size(1) if len(x.size()) > 1 else 1
    feature_offset = 1 + \
        torch.arange(0, feature_num * offset, offset, dtype=torch.long)
    x = x + feature_offset
    return x
`
I found this code in wrapper.py in your project for preprocess data but I can't understand the effect of adding an offset to the  atom feature

**Comment by huahuaai** [comment]
> Could you provide more detailed description about your question, including the reference code?



> Could you provide more detailed description about your question, including the reference code?

def convert_to_single_emb(x, offset=512): feature_num = x.size(1) if len(x.size()) > 1 else 1 feature_offset = 1 + \ torch.arange(0, feature_num * offset, offset, dtype=torch.long) x = x + feature_offset return x
I found this code in wrapper.py in your project for preprocess data but I can't understand the effect of adding an offset to the atom feature

**Comment by zhengsx** [comment]
Please have a look at previous issues #18 #28 .

**Comment by zhengsx** [comment]
Close this issue due to inactive. Feel free to raise a new one or reopen this one for any further question.
