### ISSUE TITLE
Using the code for the new dataset that we made.

### ISSUE THREAD

**Issue by gunahn** [microsoft/Graphormer#37]
I am trying to use a Graphormer on brain intelligence regression problems. So, we are using brain connectivity as an input graph, and we are trying to solve the graph regression problem. 

And we set the whole edge and node features as an integer. 

We are facing these errors below. 
`expected tensor for argument #1 'indices' to have scalar type long but got torch.FloatTensor instead`

So I tried to change the code in model.py (line 162 originally) in a diverse way.
![image](https://user-images.githubusercontent.com/58503653/143672996-893fda3a-81a2-4209-bd71-4fe0ff9fcb19.png)

However, after I changed X.type to the torch.cuda.LongTensor, I am still facing another error related to Cuda. 

![image](https://user-images.githubusercontent.com/58503653/143673034-c0342f0b-b69d-459a-bbcb-aefd5abf7a6c.png)
![image](https://user-images.githubusercontent.com/58503653/143673046-ae2aaf8f-70db-424c-8bd0-d189dbe7375a.png)

Can you help me with how to solve the problem? 

Thank You

**Comment by zhengsx** [comment]
Woud you provide more info about your error `expected tensor for argument #1 'indices' to have scalar type long but got torch.FloatTensor instead` , e.g. the complete error message, the code, and the environment you used?

**Comment by zhengsx** [comment]
Close this issue due to inactive. Feel free to raise a new one or reopen this one for any further question.
