### ISSUE TITLE
problem when using algos.pyx

### ISSUE THREAD

**Issue by jamesYu365** [microsoft/Graphormer#42]
Hello,
I got a problem while using [https://github.com/microsoft/Graphormer/blob/main/graphormer/algos.pyx](url)
Here is the error : 
```
Traceback (most recent call last):

  File "C:\Users\James\AppData\Local\Temp/ipykernel_1060/863204263.py", line 1, in <module>
    shortest_path_result, path = algos.floyd_warshall(adj.numpy())

  File "algos.pyx", line 19, in algos.floyd_warshall
    cdef numpy.ndarray[long, ndim=2, mode='c'] path = numpy.zeros([n, n], dtype=numpy.int64)

ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'
```
I'm using Windows-64bit and Python 3.8.2. Numpy version is 1.21.2

**Comment by zhengsx** [comment]
It seems that the data type defination has gap between linux and Windows. Will you try on a linux server since we have not tested our code on Windoes.

**Comment by jamesYu365** [comment]
Thanks, as you said, I work it on a linux machine and it works!

**Comment by zhengsx** [comment]
Close this issue due to inactive. Feel free to raise a new one or reopen this one for any further question.
