### ISSUE TITLE
Performance of Graphormer on traditional GNN benchmarks

### ISSUE THREAD

**Issue by CurryTang** [microsoft/Graphormer#44]
Hi! Thanks for your great work! I wonder how does Graphormer perform on some traditional GNN graph classification benchmarks (such as ones used in the original GIN paper). I've tried to apply Graphormer in my task, but the result is not very ideal without pre-training. Are pre-training and a large dataset necessary for the distinguished performance of Graphormer?

**Comment by zhengsx** [comment]
Good question. You may find some related discussions in #39 . Hope that will answer your question.
