### ISSUE TITLE
algos AttributeError

### ISSUE THREAD

**Issue by Amoy-Ou** [microsoft/Graphormer#45]
Hello:
I got an error when runing your code.Here:
```
"Graphormer/OGB-LSC/graphormer/src/ogb_wrapper.py", line 34, in preprocess_item
    all_rel_pos_3d_with_noise = torch.from_numpy(algos.bin_rel_pos_3d_1(item.all_rel_pos_3d, noise=noise)).long()
AttributeError: module 'algos' has no attribute 'bin_rel_pos_3d_1'
```

**Comment by zhengsx** [comment]
The function `bin_rel_pos_3d_1` is [here](https://github.com/microsoft/Graphormer/blob/ogb-lsc/OGB-LSC/graphormer/src/algos.pyx#L112).

**Comment by Amoy-Ou** [comment]
Thanks

**Comment by zhengsx** [comment]
Close this issue due to inactive. Feel free to raise a new one or reopen this one for any further question.
