### ISSUE TITLE
bugs in model.py line 144. 

### ISSUE THREAD

**Issue by usccolumbia** [microsoft/Graphormer#48]
in_degree, out_degree = batched_data.in_degree, batched_data.in_degree
--->
        in_degree, out_degree = batched_data.in_degree, batched_data.out_degree

**Comment by zhengsx** [comment]
Please kindly see #29 .

**Comment by zhengsx** [comment]
Close this issue due to inactive. Feel free to raise a new one or reopen this one for any further question.
