### ISSUE TITLE
Possible typo in the IS2RE processing file

### ISSUE THREAD

**Issue by KruskalLin** [microsoft/Graphormer#52]
In file `is2re.py`, should the `expand_pos_relaxed` use `pos` or `pos_relaxed`?

https://github.com/microsoft/Graphormer/blob/377cf71789b5f714c662c62d1c05e008a3463573/graphormer/tasks/is2re.py#L114

**Comment by YouJiacheng** [comment]
In current implementation, we use real_mask to only count not expanded atoms delta pos as objective in node loss, thus expanded_pos_relaxed just for padding shape.
But I agree that use pos_relaxed to expand may has more clarity.
