### ISSUE TITLE
How to use custom datasets?

### ISSUE THREAD

**Issue by Magicat128** [microsoft/Graphormer#66]
I followed https://graphormer.readthedocs.io/en/latest/Datasets.html
And it says 'fairseq-train: error: unrecognized arguments: --user-data-dir'

**Comment by shiyu1994** [comment]
@Magicat128 Thanks for using Graphormer. The customized dataset functionality was erroneously omitted in previous version. I've recover it in the main branch. Could you please try that again?

Thanks for pointing this out.

**Comment by Magicat128** [comment]
@shiyu1994 
Thanks! It works now.
Just one more error: The parameter 'seed' in [pyg_dataset.py line 21](https://github.com/microsoft/Graphormer/blob/46b38748c5586e51714eab2e21645e7166c3f6c3/graphormer/data/pyg_datasets/pyg_dataset.py#L21) doesn't match the input from [dataset.py line 78](https://github.com/microsoft/Graphormer/blob/46b38748c5586e51714eab2e21645e7166c3f6c3/graphormer/data/dataset.py#L78).

**Comment by shiyu1994** [comment]
> Just one more error: The parameter 'seed' in pyg_dataset.py line 21 doesn't match the input from dataset.py line 78.
Fixed. Could you please check now? Thanks again for finding the problem.
