### ISSUE TITLE
OSError: [Errno 12] Cannot allocate memory     self.pid = os.fork() OSError: [Errno 12] Cannot allocate memory OSError: [Errno 12] Cannot allocate memory OSError: [Errno 12] Cannot allocate memory

### ISSUE THREAD

**Issue by Frozen-here** [microsoft/Graphormer#7]
OSError: [Errno 12] Cannot allocate memory
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
OSError: [Errno 12] Cannot allocate memory
OSError: [Errno 12] Cannot allocate memory

**Comment by chengxuanying** [comment]
Our solution for KDD 2021, has lots of had-crafted features. Therefore, it takes at least 128GB memory to reproduce our result.
However, to reproduce the result shown in our paper need far less memory. Please refer to the main branch.

**Comment by zhengsx** [comment]
Close this issue due to inactivity for a long time. Feel free to reopen it if the problem still exist.
