### ISSUE TITLE
What are the main differences between Graphormer v1.0 and v2.0?

### ISSUE THREAD

**Issue by mswzeus** [microsoft/Graphormer#89]
Hi, I have a quick question about Graphormer v2.0.
What are the main differences between Graphormer v1.0 and v2.0?

- Are there any model architecture or training hyperparameter updates?
- Which factors attribute to the performance differences in PCQM4Mv1?
(https://github.com/microsoft/Graphormer/tree/main/examples/property_prediction#pcqm4mv1)
- Do you have specific reasons to use fairseq backbone? Is it for the mixed-precision training?

Thanks in advance!

**Comment by shiyu1994** [comment]
@mswzeus
> Are there any model architecture or training hyperparameter updates?

Yes. The main difference is that, Graphormer v1.0 uses pre-layernorm and v2.0 uses post-layernorm instead.

> Which factors attribute to the performance differences in PCQM4Mv1?

Our experiments show that switching from pre-layernorm to post-layernorm contributes to most of the performance gap between v1.0 and v2.0

> Do you have specific reasons to use fairseq backbone? Is it for the mixed-precision training?

We switch to fairseq backbone for efficiency. And it is easier to schedule a distributed training task with fairseq. And it is easy to extend with new models and tasks.
